[phases.setup]
nixPkgs = ["libgl1", "libglib2.0-0"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install torch==2.2.2+cpu torchvision==0.17.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu",
  "pip install -r requirements.txt"
]
